### ISSUE TITLE
How are you estimating bone rotation from Mediapipe poses?

### ISSUE THREAD

**Issue by AmitMY** [lanthaon/sl-animation-blender#2]
Really cool work!

I can't seem to find in the repo a model or algorithm that performs the pose-to-rotations transformation.
Is that something delegated to Blender to perform?

**Comment by lanthaon** [comment]
Hi Amit, thank you :)

This is right, the rotations are calculated by Blender. It happens automatically in every keyframe through the stretch-to-constraint:

https://docs.blender.org/manual/en/latest/animation/constraints/tracking/stretch_to.html
